version: '3.8'

services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password #example of a password
    extra_hosts:
      - "host.docker.internal:host-gateway"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    links:
      - mysql:db
    ports:
      - 8080:80
    environment:
      UPLOAD_LIMIT: 2G
      MEMORY_LIMIT: 2G
      MAX_EXECUTION_TIME: 600
    extra_hosts:
      - "host.docker.internal:host-gateway"
